=== ArrettB/omni-workspace/servicetrax/ims/src/main/webapp/WEB-INF/iFrame2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD for iFrame2 projects-->
<!ELEMENT action (handler+)>
<!ATTLIST action
	name CDATA #REQUIRED
>
<!ELEMENT admin EMPTY>
<!ATTLIST admin
	username CDATA #REQUIRED
	password CDATA #REQUIRED
	action CDATA #REQUIRED
	template CDATA #REQUIRED
>
<!ELEMENT appGlobalDatum (#PCDATA)>
<!ATTLIST appGlobalDatum
	name CDATA #REQUIRED
	class CDATA "java.lang.String"
>
<!ELEMENT appGlobals (appGlobalDatum | codetable | codetable2 | metadata | metadata2)*>
<!ELEMENT applicationContext (admin | appGlobals  | applicationContextListener | daemons | diagnostics | dispatcher | estimator | formatManager | integrationManager | invocationContext | mail | providers | queryFilterManager | resourceManager | sessionManager | templateManager)*>
<!ATTLIST applicationContext
	name CDATA #REQUIRED
	version CDATA #REQUIRED
	class CDATA #REQUIRED
	dynamicClassPath CDATA #IMPLIED
>
<!ELEMENT applicationContextListener EMPTY>
<!ATTLIST applicationContextListener
	class CDATA #REQUIRED
>
<!ELEMENT codetable EMPTY>
<!ATTLIST codetable
	code CDATA #REQUIRED
	id CDATA #REQUIRED
	table CDATA #REQUIRED
>
<!ELEMENT codetable2 EMPTY>
<!ATTLIST codetable2
	code CDATA #REQUIRED
	id CDATA #REQUIRED
	table CDATA #REQUIRED
>
<!ELEMENT daemons (daemon*)>
<!ELEMENT daemon EMPTY>
<!ATTLIST daemon
        name CDATA #REQUIRED
	class CDATA #REQUIRED
>
<!ELEMENT diagnostics (diagnosticsListener | diagnosticsStream | diagnosticsFile | diagnosticsApplet)*>
<!ATTLIST diagnostics
	level CDATA #REQUIRED
	port CDATA #REQUIRED
	template CDATA #REQUIRED
>
<!ELEMENT diagnosticsApplet EMPTY>
<!ATTLIST diagnosticsApplet
	codebase CDATA #REQUIRED
	level CDATA #IMPLIED
>
<!ELEMENT diagnosticsFile EMPTY>
<!ATTLIST diagnosticsFile
	level CDATA #IMPLIED
	path CDATA #REQUIRED
>
<!ELEMENT diagnosticsListener EMPTY>
<!ATTLIST diagnosticsListener
	class CDATA #REQUIRED
	name CDATA "iFrame Diagnostics"
	level CDATA #IMPLIED
>
<!ELEMENT diagnosticsMailer EMPTY>
<!ATTLIST diagnosticsMailer
	from CDATA #REQUIRED
	host CDATA #REQUIRED
	level CDATA #IMPLIED
	to CDATA #REQUIRED
>
<!ELEMENT diagnosticsStream EMPTY>
<!ATTLIST diagnosticsStream
	class CDATA #REQUIRED
	level CDATA #IMPLIED
	property CDATA #REQUIRED
>
<!ELEMENT diagnosticsLog4j EMPTY>
<!ATTLIST diagnosticsLog4j
    path CDATA #REQUIRED
    level CDATA #IMPLIED
>
<!ELEMENT dispatcher (action+)>
<!ATTLIST dispatcher
	class CDATA #REQUIRED
>
<!ELEMENT estimator (parameter*)>
<!ATTLIST estimator
	estimatorTemplate2OrgId CDATA #REQUIRED
>
<!ELEMENT formatManager (format+)>
<!ELEMENT format (#PCDATA)>
<!ATTLIST format
	name CDATA #REQUIRED
>
<!ELEMENT handler EMPTY>
<!ATTLIST handler
	class CDATA #REQUIRED
>
<!ELEMENT integrationManager EMPTY>
<!ATTLIST integrationManager
	path CDATA #REQUIRED
	notSetupMsg CDATA #REQUIRED
>
<!ELEMENT invocationContext (invocationContextListener*)>
<!ATTLIST invocationContext
	class CDATA #REQUIRED
>
<!ELEMENT invocationContextListener EMPTY>
<!ATTLIST invocationContextListener
	class CDATA #REQUIRED
>
<!ELEMENT mail EMPTY>
<!ATTLIST mail
	host CDATA #REQUIRED
	port CDATA #REQUIRED
	from CDATA #REQUIRED
>
<!ELEMENT match (#PCDATA)>
<!ELEMENT metadata EMPTY>
<!ATTLIST metadata
	table CDATA #REQUIRED
	columns CDATA #IMPLIED
>
<!ELEMENT metadata2 EMPTY>
<!ATTLIST metadata2
	table CDATA #REQUIRED
	columns CDATA #IMPLIED
>
<!--  Generic parameter-->
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED
>
<!ELEMENT provider EMPTY>
<!ATTLIST provider
	name CDATA #REQUIRED
	id CDATA #REQUIRED
	type (handler | template) #REQUIRED
>
<!ELEMENT providers (provider+)>
<!ATTLIST providers
	default CDATA #REQUIRED
>
<!ELEMENT queryFilterManager (queryFilter+)>
<!ATTLIST queryFilterManager
	class CDATA #REQUIRED
>
<!ELEMENT queryFilter EMPTY>
<!ATTLIST queryFilter
	class CDATA #REQUIRED
	name CDATA #REQUIRED
>
<!ELEMENT replace (#PCDATA)>
<!ELEMENT resource EMPTY>
<!ATTLIST resource
	default CDATA #IMPLIED
	id CDATA #REQUIRED
	max CDATA "500"
	min CDATA "1"
	name CDATA #REQUIRED
	password CDATA #IMPLIED
	ttl CDATA "100"
	type (Pooled | SingleInstance | SingleUse | SharedPool) "Pooled"
	username CDATA #IMPLIED
>
<!ELEMENT resourceManager (resourceProducer+)>
<!ATTLIST resourceManager
	class CDATA #REQUIRED
>
<!ELEMENT resourceProducer (resource+)>
<!ATTLIST resourceProducer
	class CDATA #REQUIRED
	dateFormat CDATA #REQUIRED
	driver CDATA #REQUIRED
	name CDATA #REQUIRED
	now CDATA #IMPLIED
	primaryKey CDATA #IMPLIED
	prefix CDATA #REQUIRED
>
<!ELEMENT sessionListener EMPTY>
<!ATTLIST sessionListener
	class CDATA #REQUIRED
>
<!ELEMENT sessionManager (sessionListener*)>
<!ATTLIST sessionManager
	class CDATA #REQUIRED
	persistentSession CDATA #REQUIRED
	persistentStorage CDATA #REQUIRED
	persistentTTL CDATA #REQUIRED
	bind CDATA #REQUIRED	
	ttl CDATA #REQUIRED
>
<!ELEMENT substitution (match, replace)>
<!ELEMENT templateComponent EMPTY>
<!ATTLIST templateComponent
	name CDATA #REQUIRED
	class CDATA #REQUIRED
	aSort CDATA #IMPLIED
	cellLinkClasses CDATA #IMPLIED
	chooserBasePath CDATA #IMPLIED
	dSort CDATA #IMPLIED
	filterClass CDATA #IMPLIED
	footerClass CDATA #IMPLIED
	mandFieldErrMsg CDATA #IMPLIED
	maxRows CDATA #IMPLIED
	rowClass CDATA #IMPLIED
	rowHeight CDATA #IMPLIED
	rowRolloverClass CDATA #IMPLIED
	rowSelectedClass CDATA #IMPLIED
	security CDATA #IMPLIED
	sequence CDATA #IMPLIED
	size CDATA #IMPLIED
	titleClass CDATA #IMPLIED	
	titleHeight CDATA #IMPLIED
	validate CDATA #IMPLIED	
	width CDATA #IMPLIED
>
<!ELEMENT templateManager (templateComponent | substitution)*>
<!ATTLIST templateManager
	class CDATA #REQUIRED
	path CDATA #REQUIRED
	extentions CDATA #REQUIRED
	size CDATA "200"
>

=== ArrettB/omni-workspace/servicetrax/ims/src/main/webapp/WEB-INF/ims-test.xml
<!-- DEV version of ims.xml -->

<!DOCTYPE applicationContext SYSTEM "iFrame2.dtd"
[
<!ENTITY appName "ims">
<!ENTITY projectDir "C:\Program Files\Apache Software Foundation\Tomcat 5.5\webapps\ims\">
<!ENTITY htmlDir "C:\Program Files\Apache Software Foundation\Tomcat 5.5\webapps\ims\">
<!ENTITY sep "\">
]
>

<applicationContext name="&appName;" version="ims.Version"
		    class="dynamic.intraframe.engine.BaseApplicationContext"
		>

	<admin username="admin" password="nothing" action="admin" template="iframe/adminInfo.html"/>

	<appGlobals>
		<appGlobalDatum name="additionalReports">http://www.omniworkspace.com/servicetrax</appGlobalDatum>
		<appGlobalDatum name="charmContext">stc</appGlobalDatum>
		<appGlobalDatum name="deadlockAlter">bvonhaden@apexit.com,ChrismanJ@omniworkspace.com</appGlobalDatum>
		<appGlobalDatum name="documentDir">&projectDir;documents&sep;</appGlobalDatum>
		<appGlobalDatum name="headerTitle">ServiceTRAX - Powered by Omni Workspace Company</appGlobalDatum>
		<appGlobalDatum name="ignoreContactName"> N/A</appGlobalDatum>
		<appGlobalDatum name="loginFontSize">3</appGlobalDatum>
		<appGlobalDatum name="loginTo">serviceTrax</appGlobalDatum>
		<appGlobalDatum name="loginSupport">ServiceTRAX Support 1-866-791-6664</appGlobalDatum>
		<appGlobalDatum name="loginName">User</appGlobalDatum>
		<appGlobalDatum name="maxFileSize">10000000</appGlobalDatum>
		<appGlobalDatum name="num_service_req_lock_days">3</appGlobalDatum>
		<appGlobalDatum name="num_workorder_lock_days">2</appGlobalDatum>
		<appGlobalDatum name="pocketMOTD">Please let us know how we can make PockeTRAX better 612-627-1710!</appGlobalDatum>
		<appGlobalDatum name="requestDocumentDir">&projectDir;request_documents&sep;</appGlobalDatum>
		<appGlobalDatum name="runEconnect">true</appGlobalDatum>
		<appGlobalDatum name="sendErrorsTo">bvonhaden@apexit.com</appGlobalDatum>
		<appGlobalDatum name="tempDir">&projectDir;downloadTemp&sep;</appGlobalDatum>
		<appGlobalDatum name="testEmail">bvonhaden@apexit.com</appGlobalDatum>
        <appGlobalDatum name="exchangeCalendarUrl">https://mail.omniworkspace.com/ews/exchange.asmx</appGlobalDatum>


		<appGlobalDatum name="WindowAttribs">
			'toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=yes,copyhistory=no,width=400,height=304'
		</appGlobalDatum>
		<appGlobalDatum name="Window2Attribs">
			'toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=yes,copyhistory=no'
		</appGlobalDatum>
		<appGlobalDatum name="Window2ScrollBarAttribs">
			'toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,copyhistory=no'
		</appGlobalDatum>
		<appGlobalDatum name="choose_contact/sql">
			SELECT contact_id contacts_list, contact_name display, contact_type_name type
			  FROM contacts_v
			 WHERE ext_dealer_id=&lt;?p:ext_dealer_id.toPStmtString()?&gt;
			   AND organization_id = &lt;?s:org_id.toPStmtInt()?&gt;
			 ORDER BY contact_name
		</appGlobalDatum>
 		<appGlobalDatum name="choose_customer/sql">
 			SELECT rtrim(custnmbr) ext_customer_id, rtrim(custname) display, rtrim(prbtadcd) bill_to_address_id, rtrim(prclevel) price_level_id
 			  FROM RM00101
 			 WHERE custname LIKE &lt;?p:ext_customer_id_text.concat('%').toPStmtString()?&gt; and custclas='CUSTOMER'
 		      ORDER BY custname
 		</appGlobalDatum>
 		<appGlobalDatum name="choose_dealer/sql">
 			SELECT rtrim(custnmbr) ext_dealer_id, rtrim(shrtname) display, rtrim(prbtadcd) bill_to_address_id, rtrim(prclevel) price_level_id
 			  FROM RM00101
 			 WHERE shrtname LIKE &lt;?p:ext_dealer_id_text.concat('%').toPStmtString()?&gt; and custclas='DEALER'
 		      ORDER BY shrtname
 		</appGlobalDatum>
 		<appGlobalDatum name="choose_job_location/sql">
 			SELECT job_location_id, job_location_name display
 			  FROM job_locations_v
 			 WHERE job_location_name LIKE &lt;?p:job_location_id_text.concat('%').toPStmtString()?&gt;
			   AND organization_id = &lt;?s:org_id.toPStmtInt()?&gt;
 		      ORDER BY job_location_name
 		</appGlobalDatum>
 		<appGlobalDatum name="choose_price_level/sql">
 			SELECT distinct rtrim(prclevel) ext_price_level_id, rtrim(prclevel) display
 			  FROM IV00108
 			 WHERE prclevel LIKE &lt;?p:ext_price_level_id_text.concat('%').toPStmtString()?&gt;
 		      ORDER BY ext_price_level_id
 		</appGlobalDatum>
 		<appGlobalDatum name="choose_pri_furn_line_type/sql">
 			SELECT lookup_id, lookup_name display, furniture_type_code, lookup_id AS pri_furn_line_type_id
 			  FROM furniture_line_types_v
 			 WHERE lookup_name LIKE &lt;?p:pri_furn_line_type_id_text.concat('%').toPStmtString()?&gt;
 		      ORDER BY lookup_name
 		</appGlobalDatum>
 		<appGlobalDatum name="choose_sec_furn_line_type/sql">
 			SELECT lookup_id, lookup_name display, furniture_type_code, lookup_id AS sec_furn_line_type_id
 			  FROM furniture_line_types_v
 			 WHERE lookup_name LIKE &lt;?p:sec_furn_line_type_id_text.concat('%').toPStmtString()?&gt;
 		      ORDER BY lookup_name
 		</appGlobalDatum>
 		<appGlobalDatum name="choose_case_furn_line_type/sql">
 			SELECT lookup_id, lookup_name display, furniture_type_code, lookup_id AS case_furn_line_type_id
 			  FROM furniture_line_types_v
 			 WHERE lookup_name LIKE &lt;?p:case_furn_line_type_id_text.concat('%').toPStmtString()?&gt;
 		      ORDER BY lookup_name
 		</appGlobalDatum>
 		<metadata table="request_documents" columns="name" />
	</appGlobals>

	<applicationContextListener class="ims.listeners.IMSApplicationContextListener"/>

	<daemons>
		<daemon name="EmailDaemon" class="ims.daemons.EmailDaemon"/>
		<daemon name="StatusDaemon" class="ims.daemons.StatusDaemon"/>
		<!-- daemon name="IMCommandRunner" class="ims.daemons.IMCommandRunner"/-->
	</daemons>

	<diagnostics level="15" port="19000-19099" template="iframe/diagnostics">
		<diagnosticsStream class="java.lang.System" property="out" level="15"/>
		<diagnosticsFile path="&projectDir;logs&sep;ims.log"/>
		<diagnosticsApplet codebase="/ims/jar"/>
	</diagnostics>

	<dispatcher class="dynamic.intraframe.handlers.Dispatcher">
		<action name="admin">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="dynamic.intraframe.handlers.AdminHandler"/>
		</action>
		<action name="allocate">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.billing.PoolingHandler"/>
		</action>
		<action name="archive">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.job_processing.ArchiveHandler"/>
		</action>
		<action name="changeStatus">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.job_processing.StatusHandler"/>
		</action>
		<action name="choose">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="dynamic.intraframe.handlers.ChooserHandler"/>
		</action>
		<action name="condition">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.job_processing.QuoteHandler"/>
		</action>
		<action name="confirm">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.billing.PoolingHandler"/>
		</action>
		<action name="costReport">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.job_processing.CostReportHandler"/>
		</action>
		<action name="displayChecklist">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.lists.DisplayChecklistHandler"/>
		</action>
		<action name="documentAddVersion">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.docs.DocumentAddVersionHandler"/>
		</action>
		<action name="documentDownload">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.docs.DocumentDownloadHandler"/>
		</action>
		<action name="documentLock">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.docs.DocumentLockHandler"/>
		</action>
		<action name="documentUpload">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.docs.DocumentUploadHandler"/>
		</action>
		<action name="emailSchedule">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.scheduling.EmailScheduleHandler"/>
		</action>
		<action name="enetNavSearch">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.nav.EnetSearchHandler"/>
		</action>
		<action name="exportExpenses">
			<handler class="ims.handlers.time_capture.ExportExpensesHandler"/>
		</action>
		<action name="exportPayroll">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.time_capture.ExportPayrollHandler"/>
		</action>
		<action name="expressEntry">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.time_capture.ExpressEntryHandler"/>
		</action>
		<action name="launchCharm">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.nav.LaunchCharmHandler"/>
		</action>
		<action name="loadMiscCosts">
		 	<handler class="ims.handlers.security.CheckLoginHandler"/>
			<handler class="ims.handlers.job_processing.LoadMiscCostHandler"/>
		</action>
		<action name="login">
			<handler class="ims.handlers.maintenance.UserAccessHandler"/>
			<handler class="ims.handlers.maintenance.RightsHandler"/>
			<handler class="ims.handlers.maintenance.SelectLocationHandler"/>
		</action>
		<action name="logout">
			<handler class="ims.handlers.maintenance.LogoutHandler"/>
		</action>
		<action name="modifyCustomDropList">
